# This uses the unit test in the [node.rs] file to ping all REMOTE_NODES
# and attempts to serialize their JSON data to make sure they are working.

name: Remote Node Ping
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ping
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libgtk-3-dev
    - name: Ping
      run: cargo test -- --ignored --nocapture
